language: python

python:
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"
  - "pypy"

install:
    - pip install -r requirements.txt
    - pip install -r requirements-tests.txt

script:
    - python setup.py test

notifications:
  email: false
